### ISSUE TITLE
why py-web-tool not on pypi pip

### ISSUE THREAD

**Issue by goyalyashpal** [slott56/py-web-tool#14]
https://github.com/slott56/py-web-tool/blob/bf27cb7fd6376810eee46ff298cd68caedb5a048/README#L27-L28

> This is not (currently) hosted in PyPI. Instead of installing it with PIP,
clone the GitHub repository or download the distribution kit.

why? would u need any help regarding that?

**Comment by slott56** [comment]
I don't have a **good** reason. It seems like it's only useful to folks doing development, who might also feel the need to tweak the tool.

I suppose I should take this as an upgrade request and actually take the steps to post to PyPI.

This will involve getting files like `pyproject.toml` and other things in place to make it installable.

**Comment by goyalyashpal** [comment]
> It seems like it's only useful to folks doing development, 
> who might also feel the need to tweak the tool.

thanks for sharing your thoughts. 
sharing my side: it's not at all the case for me; i use pip as a general package manager of sorts for python's distributables.

like i recently found this wonderful IDE (via this [beginnerGuide](https://wiki.python.org/moin/BeginnersGuide)) - yes, whole IDE distributed via pip; and this IDE had the most wonderful debugger i always wanted (with the ability to go backwords too)

http://thonny.org/

https://pypi.org/project/thonny
https://github.com/thonny/thonny



to be honest: ms windows is sooo broken and i have become so tired with dealing with installations on it, that i always find myself looking for distributables via package managers.

----


> I suppose I should take this as an upgrade request and actually take the steps to post to PyPI.

thanks for considerations :smiley:

**Comment by goyalyashpal** [comment]
> Other changes.
> Rename to py-web-lp to limit collisions in PyPI.
> \- @ slott56 at https://github.com/slott56/py-web-tool/pull/15

awesome: https://pypi.org/project/py-web-lp/

**Comment by goyalyashpal** [comment]
also found: 

> pylit3
> Last released Apr 7, 2019
> Python Literate Programming

via: pypi :mag: : [literate](https://pypi.org/search/?q=literate&o=)

and this one from 2013 lol: https://pypi.org/project/nanolp/

**Comment by slott56** [comment]
It might be better to open a discussion on the Wiki page instead of a closed issue.

See https://github.com/slott56/py-web-tool/wiki for a better place to put your thoughts.

**Comment by goyalyashpal** [comment]
the main point was simple, that pylit3 is also authored by you, so i was wondering on the reason for its existence in current time

https://github.com/slott56/PyLit-3
