### ISSUE TITLE
Add an open-source license

### ISSUE THREAD

**Issue by ABridgeTooFar** [slott56/py-web-tool#3]
I may have missed it, but it looks like this project does not set an explicit open-source license. The default license is that the copyright remains with you, and collaboration within the GitHub workflow becomes problematic.

If there is already an open-source license associated, can you point me to it's location?

**Comment by ABridgeTooFar** [comment]
I suggest BSD-3 as per [jgm/pandoc-filters](https://github.com/jgm/pandocfilters/blob/master/LICENSE) and (panflute)[https://github.com/sergiocorreia/panflute]

**Comment by goyalyashpal** [comment]
> (panflute)[https://github.com/sergiocorreia/panflute]

nice 😆 . i was wondering about the possibility of this mistake out in the wild some days ago, and voilla; found it (:

[panflute](https://github.com/sergiocorreia/panflute)
