### ISSUE TITLE
Native support for PanDoc AST

### ISSUE THREAD

**Issue by ABridgeTooFar** [slott56/py-web-tool#4]
During the weave phase, it would be powerful if you could make use of [PanFlute](http://scorreia.com/software/panflute/) to natively render to PanDoc's internal AST.  This would leverage the power of PanDoc to make exporting to languages other than RST much simpler.

**Comment by slott56** [comment]
Good point. This would eliminate all the hard-coded markup fragments and eliminate any subclasses of weavers. A single AST can be produced. I think I'd like to have a "stand-alone" PanFlute to RST component. Otherwise the AST can be used by PanDoc to emit other markup.

**Comment by ABridgeTooFar** [comment]
For now a separate branch maybe called withPanFlute is all that is needed to satisfy this issue.  The goal is to make sure all the elements of the PanDoc AST are expressible in the native "pyweb" markup.

web is a bit odd in that Knuth's interpretation of the word 'documentation' was actually code parseable by TeX.

RST and TeX are a bit at odds since TeX considers multiple whitespace characters to be equivalent to a single whitespace.

Once the branch is created, this discussion can be continued on the Wiki.

**Comment by slott56** [comment]
https://github.com/slott56/py-web-tool/wiki/Replacing-Markup-specific-Weaving-with-Pandoc

**Comment by ABridgeTooFar** [comment]
I don't seem to have editing privilege on that wiki page

**Comment by vo1stv** [comment]
Please close this issue and mark as "may address in future version"
